### ISSUE TITLE
报错“你配置的 defaultAI 错误”

### ISSUE THREAD

**Issue by Passerby1011** [thx114/SDGPT#1]
![image](https://user-images.githubusercontent.com/63802758/230945890-84ecc53c-8099-42d8-884d-d55340ae83c7.png)
![image](https://user-images.githubusercontent.com/63802758/230945927-1f79b9c4-01c1-4686-bc06-3e1a122aa944.png)
不知道哪有问题

**Comment by thx114** [comment]
抱歉，配置忘记更新了
cfg里应该是这样
defaultAI里只能有 ChatGPT ChatGPT_api Bing 其中一种

## cfg:

Stable-Diffusion # Stable-Diffusion 配置:
text2img_step=27 # 文生图 渲染步数
text2img_negative_prompt="(worst quality, low quality:1.4),NSFW,r18" #文生图 固定负面提示词
text2img_proxy='127.0.0.1:7860' #Stable-Diffusion api地址 (SD内配置 --server-name 127.0.0.1 --port 7860 --api)

chat # 聊天 api 通用设置:
presets_dir='./presets' # 预设文件夹
Chat_stream_waitTime=2 # 频道内 分条发送间隔 (秒)
Chat_stream_endStr=('？','。','?','\n') # 频道内 分条发送分割依据
defaultAI='ChatGPT' # 默认 AI

ChatGPT # ChatGPT 配置 (网页):
access_token="" # access_token  获取:https://chat.openai.com/api/auth/session

ChatGPT_api # ChatGPT api 配置:
api_key="" # api_key 获取:https://platform.openai.com/account/api-keys
model="gpt-3.5-turbo"

Bing # Bing api 配置:
cookies_file_path="./cookies.json" # 设置:https://github.com/thx114/SDGPT/wiki/bing-cookies

**Comment by Passerby1011** [comment]
我的里面确实只有1种啊

**Comment by Passerby1011** [comment]
![image](https://user-images.githubusercontent.com/63802758/230947172-e4ad193d-0f14-4383-ad7e-cfc110d086c4.png)
配置文件只写了chatgpt

**Comment by thx114** [comment]
cfg生成错误 已修复
